//PRODUCTS TYPES
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_CATEGORY = "GET_PRODUCTS_CATEGORY";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
export const CLEAR_FILTER = "CLEAR_FILTER";
//CART TYPES
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const GET_ALL_CART = "GET_ALL_CART";
export const MENU_SLIDE_TOGGLE = "MENU_SLIDE_TOGGLE";
export const SHOPPING_CART_TOGGLE = "SHOPPING_CART_TOGGLE";
//AUTHENTICATION AND ERRORS
export const ERROR = "ERROR";
export const IS_AUTHENTICATED = "IS_AUTHENTICATED";
export const IS_NOT_AUTHENTICATED = "IS_NOT_AUTHENTICATED";
//LOADING
export const SET_LOADING = "SET_LOADING";
